# Generated by Django 5.2.11 on 2026-08-07 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgcode_enterprise', '0002_alter_orgcode_code_alter_orgcode_discount_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('requires_accreditation_fields', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseLearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('admin', 'Administrator')], db_index=True, default='student', max_length=32)),
                ('honorific', models.CharField(blank=True, max_length=32)),
                ('middle_initial', models.CharField(blank=True, max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=32)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=32)),
                ('timezone', models.CharField(default='America/New_York', max_length=64)),
                ('student_identifier', models.CharField(blank=True, db_index=True, max_length=64)),
                ('organization_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerAccreditationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(blank=True, choices=[('hispanic_or_latino', 'Hispanic or Latino'), ('not_hispanic_or_latino', 'Not Hispanic or Latino')], max_length=64)),
                ('race', models.CharField(blank=True, choices=[('american_indian_or_alaska_native', 'American Indian or Alaska Native'), ('asian', 'Asian'), ('black_or_african_american', 'Black or African American'), ('native_hawaiian_or_other_pacific_islander', 'Native Hawaiian or Other Pacific Islander'), ('white', 'White'), ('some_other_race', 'Some Other Race'), ('two_or_more_races', 'Two or More Races')], max_length=64)),
                ('veteran_status', models.CharField(choices=[('non_veteran', 'Non Veteran'), ('veteran', 'Veteran'), ('disabled_veteran', 'Disabled Veteran'), ('spouse_of_veteran', 'Spouse of a Veteran')], db_index=True, default='non_veteran', max_length=64)),
                ('branch_of_service', models.CharField(blank=True, choices=[('army', 'Army'), ('marine_corps', 'Marine Corps'), ('navy', 'Navy'), ('air_force', 'Air Force'), ('space_force', 'Space Force'), ('coast_guard', 'Coast Guard')], max_length=64)),
                ('citizenship', models.CharField(blank=True, choices=[('united_states', 'United States'), ('permanent_resident', 'Permanent Resident'), ('not_us_citizen_or_permanent_resident', 'Not a United States Citizen or Permanent Resident')], max_length=100)),
                ('education_level', models.CharField(blank=True, choices=[('less_than_high_school', 'Less than High School'), ('high_school_graduate_or_ged', 'High School Graduate or GED'), ('some_college_or_technical_training', 'Some College or Technical Training'), ('college_graduate_or_higher', 'College Graduate or Higher')], max_length=100)),
                ('english_proficiency', models.CharField(blank=True, choices=[('native_speaker', 'Native speaker'), ('fluent', 'Fluent (can speak, read, and write easily)'), ('conversational', 'Conversational (can handle everyday situations)'), ('basic', 'Basic (know some words and phrases)'), ('none', 'No English proficiency')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accreditation', to='orgcode_enterprise.enterpriselearnerprofile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LearnerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='United States', max_length=64)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='orgcode_enterprise.enterpriselearnerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('requires_accreditation_fields', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_programs', to='orgcode_enterprise.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CertificateProgramEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='active', max_length=32)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_enrollments', to='orgcode_enterprise.certificateprogram')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_program_enrollments', to='orgcode_enterprise.enterpriselearnerprofile')),
            ],
            options={
                'unique_together': {('profile', 'program')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='orgcode_enterprise.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to='orgcode_enterprise.enterpriselearnerprofile')),
            ],
            options={
                'unique_together': {('profile', 'organization')},
            },
        ),
    ]
