# Generated by Django 5.2.12 on 2026-09-18 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def reconcile_legacy_mysql_primary_keys(apps, schema_editor):
    """Align legacy integer keys with the BigAutoField migration state."""

    connection = schema_editor.connection
    if connection.vendor != "mysql":
        return

    orgcode_table = "orgcode_enterprise_orgcode"
    usage_table = "orgcode_enterprise_orgcodeusage"
    fallback_fk_name = "orgcode_enterprise_orgcodeusage_code_id_56f77375_fk"
    quote = schema_editor.quote_name

    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT table_name, column_name, data_type
            FROM information_schema.columns
            WHERE table_schema = DATABASE()
              AND (
                    (table_name = %s AND column_name = 'id')
                 OR (table_name = %s AND column_name IN ('id', 'code_id'))
              )
            """,
            [orgcode_table, usage_table],
        )
        column_types = {
            (table_name, column_name): data_type.lower()
            for table_name, column_name, data_type in cursor.fetchall()
        }
        expected_columns = {
            (orgcode_table, "id"),
            (usage_table, "id"),
            (usage_table, "code_id"),
        }
        if set(column_types) != expected_columns:
            missing = sorted(expected_columns - set(column_types))
            raise RuntimeError(
                f"Cannot reconcile OrgCode primary keys; missing columns: {missing}"
            )

        cursor.execute(
            """
            SELECT
                kcu.constraint_name,
                rc.delete_rule,
                rc.update_rule
            FROM information_schema.key_column_usage AS kcu
            JOIN information_schema.referential_constraints AS rc
              ON rc.constraint_schema = kcu.constraint_schema
             AND rc.constraint_name = kcu.constraint_name
             AND rc.table_name = kcu.table_name
            WHERE kcu.constraint_schema = DATABASE()
              AND kcu.table_name = %s
              AND kcu.column_name = 'code_id'
              AND kcu.referenced_table_name = %s
              AND kcu.referenced_column_name = 'id'
            """,
            [usage_table, orgcode_table],
        )
        foreign_keys = cursor.fetchall()

        already_bigint = all(
            column_types[column] == "bigint" for column in expected_columns
        )
        if already_bigint and foreign_keys:
            return

        for constraint_name, _delete_rule, _update_rule in foreign_keys:
            cursor.execute(
                f"ALTER TABLE {quote(usage_table)} "
                f"DROP FOREIGN KEY {quote(constraint_name)}"
            )

        cursor.execute(
            f"ALTER TABLE {quote(orgcode_table)} "
            f"MODIFY COLUMN {quote('id')} BIGINT NOT NULL AUTO_INCREMENT"
        )
        cursor.execute(
            f"ALTER TABLE {quote(usage_table)} "
            f"MODIFY COLUMN {quote('id')} BIGINT NOT NULL AUTO_INCREMENT, "
            f"MODIFY COLUMN {quote('code_id')} BIGINT NOT NULL"
        )

        constraint_name = foreign_keys[0][0] if foreign_keys else fallback_fk_name
        delete_rule = foreign_keys[0][1] if foreign_keys else "NO ACTION"
        update_rule = foreign_keys[0][2] if foreign_keys else "NO ACTION"
        allowed_rules = {"CASCADE", "RESTRICT", "SET NULL", "NO ACTION"}
        if delete_rule not in allowed_rules or update_rule not in allowed_rules:
            raise RuntimeError("Unsupported legacy foreign-key action.")

        cursor.execute(
            f"ALTER TABLE {quote(usage_table)} "
            f"ADD CONSTRAINT {quote(constraint_name)} "
            f"FOREIGN KEY ({quote('code_id')}) "
            f"REFERENCES {quote(orgcode_table)} ({quote('id')}) "
            f"ON DELETE {delete_rule} ON UPDATE {update_rule}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('orgcode_enterprise', '0003_enterprise_identity_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            reconcile_legacy_mysql_primary_keys,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='AccessPolicyCoursePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('course_key',),
            },
        ),
        migrations.CreateModel(
            name='AccessPolicyProgramPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ('program_code',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('access_policy__key', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='certificateprogram',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='learneraccreditationrecord',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='orgcode',
            options={'ordering': ('organization__name', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='certificateprogramenrollment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='orgcodeusage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='organization',
            name='enterprise_customer_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='orgcode',
            name='code_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orgcode',
            name='code_prefix',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='orgcode',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_codes', to='orgcode_enterprise.organization'),
        ),
        migrations.AlterField(
            model_name='orgcodeusage',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='orgcode_enterprise.orgcode'),
        ),
        migrations.AlterField(
            model_name='orgcodeusage',
            name='times_used',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='certificateprogramenrollment',
            constraint=models.UniqueConstraint(fields=('profile', 'program'), name='orgcode_unique_profile_program'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('profile', 'organization'), name='orgcode_unique_profile_org'),
        ),
        migrations.AddConstraint(
            model_name='orgcodeusage',
            constraint=models.UniqueConstraint(fields=('user', 'code'), name='orgcode_unique_user_code_usage'),
        ),
        migrations.AddField(
            model_name='orgcode',
            name='access_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_codes', to='orgcode_enterprise.accesspolicy'),
        ),
        migrations.AddField(
            model_name='accesspolicycoursepermission',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_permissions', to='orgcode_enterprise.accesspolicy'),
        ),
        migrations.AddField(
            model_name='accesspolicyprogrampermission',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_permissions', to='orgcode_enterprise.accesspolicy'),
        ),
        migrations.AddField(
            model_name='organizationaccessgrant',
            name='access_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='orgcode_enterprise.accesspolicy'),
        ),
        migrations.AddField(
            model_name='organizationaccessgrant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='orgcode_enterprise.organization'),
        ),
        migrations.AddField(
            model_name='organizationaccessgrant',
            name='source_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='orgcode_enterprise.orgcode'),
        ),
        migrations.AddField(
            model_name='organizationaccessgrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='accesspolicycoursepermission',
            constraint=models.UniqueConstraint(fields=('policy', 'course_key'), name='orgcode_unique_policy_course'),
        ),
        migrations.AddConstraint(
            model_name='accesspolicyprogrampermission',
            constraint=models.UniqueConstraint(fields=('policy', 'program_code'), name='orgcode_unique_policy_program'),
        ),
        migrations.AddConstraint(
            model_name='organizationaccessgrant',
            constraint=models.UniqueConstraint(fields=('user', 'organization', 'access_policy'), name='orgcode_unique_user_org_policy'),
        ),
    ]
