# Generated by Django 5.2.12 on 2026-09-18 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgcode_enterprise', '0003_enterprise_identity_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='AccessPolicyCoursePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('course_key',),
            },
        ),
        migrations.CreateModel(
            name='AccessPolicyProgramPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ('program_code',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('access_policy__key', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='certificateprogram',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='learneraccreditationrecord',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='orgcode',
            options={'ordering': ('organization__name', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='certificateprogramenrollment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='orgcodeusage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='organization',
            name='enterprise_customer_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='orgcode',
            name='code_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orgcode',
            name='code_prefix',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='orgcode',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_codes', to='orgcode_enterprise.organization'),
        ),
        migrations.AlterField(
            model_name='orgcodeusage',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='orgcode_enterprise.orgcode'),
        ),
        migrations.AlterField(
            model_name='orgcodeusage',
            name='times_used',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='certificateprogramenrollment',
            constraint=models.UniqueConstraint(fields=('profile', 'program'), name='orgcode_unique_profile_program'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('profile', 'organization'), name='orgcode_unique_profile_org'),
        ),
        migrations.AddConstraint(
            model_name='orgcodeusage',
            constraint=models.UniqueConstraint(fields=('user', 'code'), name='orgcode_unique_user_code_usage'),
        ),
        migrations.AddField(
            model_name='orgcode',
            name='access_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_codes', to='orgcode_enterprise.accesspolicy'),
        ),
        migrations.AddField(
            model_name='accesspolicycoursepermission',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_permissions', to='orgcode_enterprise.accesspolicy'),
        ),
        migrations.AddField(
            model_name='accesspolicyprogrampermission',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_permissions', to='orgcode_enterprise.accesspolicy'),
        ),
        migrations.AddField(
            model_name='organizationaccessgrant',
            name='access_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='orgcode_enterprise.accesspolicy'),
        ),
        migrations.AddField(
            model_name='organizationaccessgrant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='orgcode_enterprise.organization'),
        ),
        migrations.AddField(
            model_name='organizationaccessgrant',
            name='source_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='orgcode_enterprise.orgcode'),
        ),
        migrations.AddField(
            model_name='organizationaccessgrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='accesspolicycoursepermission',
            constraint=models.UniqueConstraint(fields=('policy', 'course_key'), name='orgcode_unique_policy_course'),
        ),
        migrations.AddConstraint(
            model_name='accesspolicyprogrampermission',
            constraint=models.UniqueConstraint(fields=('policy', 'program_code'), name='orgcode_unique_policy_program'),
        ),
        migrations.AddConstraint(
            model_name='organizationaccessgrant',
            constraint=models.UniqueConstraint(fields=('user', 'organization', 'access_policy'), name='orgcode_unique_user_org_policy'),
        ),
    ]
