# Generated by Django 5.2.12 on 2026-09-18 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgcode_enterprise', '0005_hash_codes_and_migrate_legacy_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriselearnerprofile',
            name='organization_code',
        ),
        migrations.RemoveField(
            model_name='orgcode',
            name='code',
        ),
        migrations.RemoveField(
            model_name='orgcode',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='orgcode',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='orgcode',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='orgcode',
            name='program_id',
        ),
        migrations.AlterField(
            model_name='orgcode',
            name='access_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_codes', to='orgcode_enterprise.accesspolicy'),
        ),
        migrations.AlterField(
            model_name='orgcode',
            name='code_hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orgcode',
            name='code_prefix',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='orgcode',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_codes', to='orgcode_enterprise.organization'),
        ),
    ]
