# Generated by Django 5.2.13 on 2026-09-24 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgcode_enterprise', '0006_remove_plaintext_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('priority', 'key'),
            },
        ),
        migrations.CreateModel(
            name='EnrollmentInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('course', 'Course'), ('program', 'Certificate Program')], max_length=16)),
                ('product_key', models.CharField(db_index=True, max_length=255)),
                ('audience', models.CharField(choices=[('public', 'Public'), ('organization', 'Organization')], default='public', max_length=32)),
                ('scope_key', models.CharField(db_index=True, editable=False, max_length=160)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('release_on_unenrollment', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('access_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_inventories', to='orgcode_enterprise.accesspolicy')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_inventories', to='orgcode_enterprise.organization')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='orgcode_enterprise.promotioncampaign')),
            ],
            options={
                'ordering': ('campaign__priority', 'product_type', 'product_key', 'scope_key'),
            },
        ),
        migrations.CreateModel(
            name='PromotionOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
                ('tier_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='orgcode_enterprise.enrollmentinventory')),
            ],
            options={
                'ordering': ('inventory', 'priority', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EnrollmentReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('reserved', 'Reserved'), ('committed', 'Committed'), ('released', 'Released'), ('expired', 'Expired')], db_index=True, default='reserved', max_length=16)),
                ('source', models.CharField(choices=[('course_filter', 'Course Enrollment Filter'), ('program_api', 'Program Enrollment API'), ('administrative', 'Administrative'), ('reconciliation', 'Reconciliation')], max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('enrollment_reference', models.CharField(blank=True, max_length=255)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='orgcode_enterprise.enrollmentinventory')),
                ('organization_access_grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_reservations', to='orgcode_enterprise.organizationaccessgrant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_reservations', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='orgcode_enterprise.promotionoffer')),
            ],
            options={
                'ordering': ('-reserved_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='enrollmentinventory',
            constraint=models.UniqueConstraint(fields=('campaign', 'product_type', 'product_key', 'scope_key'), name='orgcode_unique_campaign_inventory'),
        ),
        migrations.AddConstraint(
            model_name='promotionoffer',
            constraint=models.UniqueConstraint(fields=('inventory', 'priority'), name='orgcode_unique_inventory_offer_priority'),
        ),
        migrations.AddIndex(
            model_name='enrollmentreservation',
            index=models.Index(fields=['state', 'expires_at'], name='orgcode_res_state_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentreservation',
            index=models.Index(fields=['user', 'state'], name='orgcode_res_user_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentreservation',
            constraint=models.UniqueConstraint(fields=('inventory', 'user'), name='orgcode_unique_inventory_user_reservation'),
        ),
    ]
